org: abnerpersio
service: wsapi

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    CONNECTIONS_TABLE: !Ref ConnectionsTable
    WEBSOCKETS_API: !Join ['', ['https://', !Ref WebsocketsApi, '.execute-api.', '${self:provider.region}', '.amazonaws.com/', '${self:provider.stage}']]
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: !GetAtt ConnectionsTable.Arn

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  ws-connection:
    handler: src/functions/ws-connection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  ws-send-message:
    handler: src/functions/ws-send-message.handler
    events:
      - websocket:
          route: sendMessage
  ws-garbage-collector:
    handler: src/functions/ws-garbage-collector.handler
    events:
      - eventBridge:
        schedule: rate(1 minute)

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
